name: shrine
description: Learn the basics of using Material Components by building a simple app with core components.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.5
  shrine_images: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  # TODO: Insert Fonts (103)
  uses-material-design: true
  assets:
    - assets/logo.png
    # TODO: Add slanted menu asset (104)
    - assets/Buket Mawar Merah Classic.jpg
    - assets/Buket Mawar Pink.jpg
    - assets/Buket Mawar Biru Premium.jpg
    - assets/Buket Tulip Mix.jpg
    - assets/Buket Lili Putih.jpg
    - assets/Buket Anggrek Ungu.jpg
    - assets/Bunga Gerbera Colorful.jpg
    - assets/Buket Mix Rose & Babys Breath.jpg
    - assets/Buket Bunga Anyelir.jpg
    - assets/Buket Calla Lily Putih.jpg
    - assets/Buket Hydrangea Biru.jpg
    - assets/Buket Daisy Putih Manis.jpg
    - assets/Peony Pink.jpg
    - assets/Buket Mix Sunflower & Krisan.jpg
    - assets/Lily Oriental.jpg
    - assets/Bunga Dahlia.jpg
    - assets/Lavender.jpg
    - assets/Alamanda.jpg
    - assets/Frangipani.jpg
    - assets/Amaryllis.jpg
    - assets/Ranunculus.jpg
    - assets/Freesia.jpg
    - assets/Scabiosa.jpg
    - assets/Calla Lily.jpg
    - assets/Delphinium.jpg
    - assets/Bunga Matahari.jpg
    - assets/Cornflower.jpg
    - assets/Sweet Pea.jpg
    - assets/Gardenia.jpg
    - assets/Protea.jpg
    - assets/Lupin.jpg
    - assets/Strelitzia.jpg
    - assets/Wedding Buket.jpg
    - assets/Mawar Pink.jpg
    - assets/Bunga Scilla.jpg
    - assets/Bunga Astilbe.jpg
    - assets/Lily.jpg
    - assets/Mawar Putih.jpg
    